# Generated by Django 4.0.3 on 2022-03-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس دسته بندی')),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='store.category', verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='ساعت')),
                ('photo', models.ImageField(upload_to='%Y/%m/%d', verbose_name='تصویر')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
