# Generated by Django 4.0.3 on 2022-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
