# Generated by Django 4.0.3 on 2022-03-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='تصویر'),
        ),
    ]
